version: '3.9'

#networks:
#  dev_network:

services:

  redis-upscaleapp:
    image: redis:7.0.0-alpine3.15
    ports:
      - "6379:6379"
    depends_on:
      - postgres-upscaleapp
    container_name: redis_upscale_app
  #    networks:
  #      dev_network:
  #        aliases:
  #          - db-redis

  postgres-upscaleapp:
    image: postgres:14.3-alpine3.16
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: 1234_secret
      POSTGRES_DB: app
    container_name: postgres_upscale_app
  #    networks:
  #      dev_network:
  #        aliases:
  #          - db-postgre

  mongo-upscaleapp:
    image: mongo:4.4.14
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: app
      MONGO_INITDB_ROOT_PASSWORD: 1234_secret
    depends_on:
      - redis-upscaleapp
    container_name: mongo_upscale_app
#    networks:
#      dev_network:
#        aliases:
#          - db-mongo
